title: ZhangShuoNing's Homepage
page-top-title: ZhangShuoNing
top-section-bg-text: Fighting entropy in chaotic life 
home-subtitle: ZhangShuoNing&ensp;|&ensp;张朔宁
copyright-text: '&copy; ZhangShuoNing 2023-2025. All Rights Reserved.'
